//
//  NoteChatModel.swift
//  NotifyAIServices
//

import Foundation
import NotifyAICore
import Observation
import OSLog

/// A passage an answer is based on, shown as a tappable source card.
public struct ChatSource: Identifiable, Hashable, Sendable {
    public let number: Int
    public let noteID: UUID
    public let noteTitle: String
    public let noteDate: Date
    let noteKind: NoteKind
    public let start: TimeInterval?
    public let excerpt: String
    public let isSummary: Bool
    public var id: Int { number }
}

/// A note that matches the question.
public struct ChatNoteLink: Identifiable, Hashable, Sendable {
    public let noteID: UUID
    public let title: String
    public let date: Date
    public let kind: NoteKind
    public let reasons: [String]
    public var id: UUID { noteID }
}

public struct ChatMessage: Identifiable, Sendable {
    public enum Role: Sendable {
        case user
        case assistant
    }

    public let id = UUID()
    public let role: Role
    public var text: String
    public var sources: [ChatSource] = []
    public var notes: [ChatNoteLink] = []
    /// The filters the question was understood with ("Letzte Woche", "Person: Anna").
    public var filters: [String] = []
    /// Additional information, e.g. that the answer was not generated by the language model.
    public var notice: String?
    public var isPending = false
}

/// "Notizen fragen": questions in natural language about all notes.
///
/// Pipeline for every question:
/// 1. **Understand** – rules (dates, known names, kinds) plus, with Apple Intelligence, a
///    structured search plan (rewritten query, synonyms, people, time frame, follow-ups).
/// 2. **Retrieve** – hybrid full-text and semantic search with the filters applied.
/// 3. **Answer** – the language model answers from the best passages only and cites them.
///    Without Apple Intelligence the best passages are shown directly.
@MainActor
@Observable
public final class NoteChatModel {
    public private(set) var messages: [ChatMessage] = []
    public private(set) var isResponding = false

    @ObservationIgnored private let knowledge: KnowledgeIndexService
    @ObservationIgnored private let settings: AppSettings
    @ObservationIgnored private let assistant: any NoteAssistant
    @ObservationIgnored private let availability: @Sendable (TranscriptionLanguage) -> LanguageModelAvailability
    @ObservationIgnored private let now: @Sendable () -> Date
    @ObservationIgnored private var responseTask: Task<Void, Never>?
    @ObservationIgnored private let logger = Logger.summarization

    /// Tokens for the sources of one answer. The on-device model has a context of 4096
    /// tokens; instructions, question, history and the answer need the rest.
    static let sourceTokenBudget = 2_000
    static let maximumSourceCharacters = 900
    static let maximumSources = 8

    public static let suggestions = [
        String(localized: "Welche Aufgaben habe ich diese Woche übernommen?", bundle: .module),
        String(localized: "Was wurde zuletzt entschieden?", bundle: .module),
        String(localized: "Welche Fragen sind noch offen?", bundle: .module),
        String(localized: "Zeig mir alle Aufnahmen von letzter Woche", bundle: .module),
    ]

    init(
        knowledge: KnowledgeIndexService,
        settings: AppSettings,
        assistant: any NoteAssistant = FoundationModelNoteAssistant(),
        availability: @escaping @Sendable (TranscriptionLanguage) -> LanguageModelAvailability = LanguageModelAvailability.current,
        now: @escaping @Sendable () -> Date = { .now }
    ) {
        self.knowledge = knowledge
        self.settings = settings
        self.assistant = assistant
        self.availability = availability
        self.now = now
    }

    public var modelAvailability: LanguageModelAvailability {
        availability(settings.transcription.language)
    }

    public func send(_ question: String) {
        let question = question.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !question.isEmpty, !isResponding else { return }
        let history = completedTurns()
        messages.append(ChatMessage(role: .user, text: question))
        messages.append(ChatMessage(role: .assistant, text: "", isPending: true))
        isResponding = true
        responseTask = Task { [weak self] in
            guard let self else { return }
            let answer = await respond(to: question, history: history)
            guard !Task.isCancelled else { return }
            if let index = messages.lastIndex(where: { $0.isPending }) {
                messages[index] = answer
            }
            isResponding = false
            responseTask = nil
        }
    }

    public func cancel() {
        responseTask?.cancel()
        responseTask = nil
        messages.removeAll { $0.isPending }
        isResponding = false
    }

    public func reset() {
        cancel()
        messages.removeAll()
    }

    // MARK: - Pipeline

    /// Answers one question. Internal for tests.
    func respond(to question: String, history: [ChatTurn]) async -> ChatMessage {
        await knowledge.refreshAndWait()
        let index = knowledge.index
        guard !index.notes.isEmpty else {
            return ChatMessage(
                role: .assistant,
                text: String(localized: "Es gibt noch keine fertigen Notizen, die ich durchsuchen kann. Sobald eine Aufnahme oder ein Import verarbeitet ist, kannst du hier Fragen dazu stellen.", bundle: .module)
            )
        }

        let date = now()
        let canUseModel = modelAvailability == .available
        let plan = await makePlan(for: question, history: history, index: index, now: date, useModel: canUseModel)
        let request = SearchRequest(
            text: plan.searchText,
            expansions: plan.expansions,
            filters: plan.filters,
            languageCode: settings.transcription.language.languageCode
        )
        let result = await Self.search(request, in: index, embedder: knowledge.embedder)

        var message = ChatMessage(role: .assistant, text: "", filters: plan.filterDescriptions)
        message.notes = result.notes.map {
            ChatNoteLink(noteID: $0.note.id, title: $0.note.title, date: $0.note.createdAt, kind: $0.note.kind, reasons: $0.reasons)
        }
        if !result.relaxedPersons.isEmpty {
            message.notice = String(localized: "Keine Notiz erwähnt \(result.relaxedPersons.joined(separator: ", ")). Ich habe ohne diesen Filter gesucht.", bundle: .module)
        }

        guard result.candidateCount > 0 else {
            message.text = String(localized: "Für diese Filter gibt es keine Notizen.", bundle: .module)
            return message
        }
        guard !result.passages.isEmpty || !result.notes.isEmpty else {
            message.text = String(localized: "Dazu habe ich in deinen Notizen nichts gefunden.", bundle: .module)
            return message
        }

        // Lists ("Zeig mir alle Meetings mit Anna") need no generated answer.
        let isListing = plan.wantsList || TextAnalysis.terms(in: plan.searchText, languageCode: request.languageCode).isEmpty && plan.expansions.isEmpty
        if isListing {
            message.text = result.notes.count == 1
                ? String(localized: "Ich habe eine passende Notiz gefunden.", bundle: .module)
                : String(localized: "Ich habe \(result.notes.count) passende Notizen gefunden.", bundle: .module)
            return message
        }

        let sources = selectSources(from: result.passages)
        guard canUseModel else {
            message.text = String(localized: "Das sind die passendsten Stellen in deinen Notizen:", bundle: .module)
            message.sources = Array(sources.prefix(5))
            message.notice = [message.notice, Self.unavailableNotice(modelAvailability)].compactMap { $0 }.joined(separator: " ")
            return message
        }

        await answer(question, from: sources, history: history, now: date, into: &message)
        return message
    }

    @concurrent
    private static func search(_ request: SearchRequest, in index: KnowledgeIndex, embedder: any SentenceEmbedding) async -> SearchResult {
        HybridRetriever(index: index, embedder: embedder).search(request)
    }

    /// Lets the language model answer from the sources and keeps only the sources it cited.
    /// Without an answer, the best passages are shown instead.
    private func answer(_ question: String, from sources: [ChatSource], history: [ChatTurn], now date: Date, into message: inout ChatMessage) async {
        do {
            let answer = try await assistant.answer(
                question: question,
                sources: sources.map {
                    AssistantSource(number: $0.number, noteTitle: $0.noteTitle, noteDate: $0.noteDate, start: $0.start, text: $0.excerpt)
                },
                history: history,
                language: settings.transcription.language,
                now: date
            )
            message.text = answer.text
            if answer.isAnswerFound {
                let cited = answer.citedSources.compactMap { number in sources.first { $0.number == number } }
                message.sources = cited.isEmpty ? Array(sources.prefix(3)) : cited
            } else {
                message.notice = [message.notice, String(localized: "Die passendsten Notizen findest du unten.", bundle: .module)]
                    .compactMap { $0 }
                    .joined(separator: " ")
            }
        } catch is CancellationError {
            message.text = ""
        } catch {
            logger.error("Answering a question failed: \(error.localizedDescription, privacy: .public)")
            message.text = String(localized: "Das sind die passendsten Stellen in deinen Notizen:", bundle: .module)
            message.sources = Array(sources.prefix(5))
            message.notice = [message.notice, String(localized: "Apple Intelligence konnte keine Antwort formulieren.", bundle: .module)]
                .compactMap { $0 }
                .joined(separator: " ")
        }
    }

    /// Rules first; the language model adds synonyms, people and a time frame the rules missed.
    private func makePlan(for question: String, history: [ChatTurn], index: KnowledgeIndex, now: Date, useModel: Bool) async -> QueryPlan {
        var plan = RuleBasedQueryParser(now: now).plan(for: question, knownPersons: index.knownPersons)
        guard useModel else { return plan }
        do {
            let generated = try await assistant.plan(question: question, history: history, now: now)
            Self.merge(generated, into: &plan, now: now)
        } catch {
            logger.error("Planning the search failed: \(error.localizedDescription, privacy: .public)")
        }
        return plan
    }

    /// Internal for tests.
    nonisolated static func merge(_ generated: AssistantPlan, into plan: inout QueryPlan, now: Date, calendar: Calendar = .current) {
        if !generated.searchQuery.isEmpty {
            plan.searchText = generated.searchQuery
        }
        plan.expansions = generated.relatedTerms
        // Explicit time expressions found by the rules win; the model covers the rest.
        if plan.filters.dateRange == nil, generated.timeframe != .none,
           let range = generated.timeframe.dateRange(now: now, calendar: calendar) {
            plan.filters.dateRange = range
            plan.filterDescriptions.append(generated.timeframe.title)
        }
        for person in generated.persons where !plan.filters.persons.contains(where: { HybridRetriever.name($0, matches: person) }) {
            plan.filters.persons.append(person)
            plan.filterDescriptions.append(String(localized: "Person: \(person)", bundle: .module))
        }
        plan.wantsList = plan.wantsList || generated.wantsList
    }

    /// Numbered sources within the token budget, best first.
    private func selectSources(from hits: [PassageHit]) -> [ChatSource] {
        var sources: [ChatSource] = []
        var tokens = 0
        for hit in hits {
            let excerpt = hit.passage.text.count > Self.maximumSourceCharacters
                ? String(hit.passage.text.prefix(Self.maximumSourceCharacters)) + " …"
                : hit.passage.text
            let cost = excerpt.count / 3 + 30
            if !sources.isEmpty, tokens + cost > Self.sourceTokenBudget { break }
            tokens += cost
            sources.append(ChatSource(
                number: sources.count + 1,
                noteID: hit.note.id,
                noteTitle: hit.note.title,
                noteDate: hit.note.createdAt,
                noteKind: hit.note.kind,
                start: hit.passage.start,
                excerpt: excerpt,
                isSummary: hit.passage.kind == .summary
            ))
            if sources.count == Self.maximumSources { break }
        }
        return sources
    }

    private func completedTurns() -> [ChatTurn] {
        var turns: [ChatTurn] = []
        var pendingQuestion: String?
        for message in messages where !message.isPending {
            switch message.role {
            case .user:
                pendingQuestion = message.text
            case .assistant:
                if let question = pendingQuestion {
                    turns.append(ChatTurn(question: question, answer: message.text))
                    pendingQuestion = nil
                }
            }
        }
        return Array(turns.suffix(3))
    }

    private static func unavailableNotice(_ availability: LanguageModelAvailability) -> String? {
        guard case .unavailable(let reason) = availability else { return nil }
        return String(localized: "\(reason) Ohne Apple Intelligence zeige ich die passenden Stellen statt einer formulierten Antwort.", bundle: .module)
    }
}
